In [1]:
import numpy as np
import math

# ===== Câu 1a =====
A = np.array([2, -1, 3, 0])
B = np.array([1, 4, -2, 5])

A_plus_B = A + B
three_A_minus_two_B = 3 * A - 2 * B

print("Câu 1a:")
print("A + B =", A_plus_B)
print("3A - 2B =", three_A_minus_two_B)

# ===== Câu 1b =====
dot_product = np.dot(A, B)
norm_A = np.linalg.norm(A)
norm_B = np.linalg.norm(B)
cos_theta = dot_product / (norm_A * norm_B)
theta_deg = np.degrees(np.arccos(cos_theta))

print("\nCâu 1b:")
print("Tích vô hướng A · B =", dot_product)
print("Góc giữa A và B (độ) ≈", round(theta_deg, 3))

# ===== Câu 1c =====
C = np.array([
    [1, 2, -1],
    [0, 3, 4],
    [2, -1, 0]
])

CT = C.T
CTC = np.matmul(CT, C)

print("\nCâu 1c:")
print("C^T * C =\n", CTC)

Câu 1a:
A + B = [3 3 1 5]
3A - 2B = [  4 -11  13 -10]

Câu 1b:
Tích vô hướng A · B = -8
Góc giữa A và B (độ) ≈ 108.376

Câu 1c:
C^T * C =
 [[ 5  0 -1]
 [ 0 14 10]
 [-1 10 17]]


In [7]:
import numpy as np

# ===== Câu 2: Dữ liệu =====
M = np.array([
    [1, 2, 3, 0],
    [4, 5, 6, 1],
    [7, 8, 9, 2],
    [0, 1, 1, 0]
])

N = np.array([
    [0, 1, 2, 3],
    [4, 5, 6, 7],
    [8, 9, 10, 11],
    [12, 13, 14, 15]
])

# ===== a) Tích M x N =====
product_MN = np.matmul(M, N)

print("Câu 2a: M x N =")
print(product_MN)

# ===== b) Định thức của M =====
det_M = np.linalg.det(M)
print("\nCâu 2b: Định thức của M =", round(det_M, 2))

if det_M == 0:
    print("→ M không khả nghịch (vì det = 0)")

# ===== c) Hạng của N =====
rank_N = np.linalg.matrix_rank(N)
print("\nCâu 2c: Hạng của N =", rank_N)

Câu 2a: M x N =
[[ 32  38  44  50]
 [ 80  96 112 128]
 [128 154 180 206]
 [ 12  14  16  18]]

Câu 2b: Định thức của M = 0.0

Câu 2c: Hạng của N = 2


In [8]:
import numpy as np

# ===== Câu 3: Dữ liệu =====
P = np.array([
    [2, 1, 0, 1],
    [0, 3, 1, -1],
    [1, 0, 4, 2],
    [0, 1, 0, 3]
])

b = np.array([4, 7, 9, 5])

# ===== a) Tính nghịch đảo của P =====
try:
    P_inv = np.linalg.inv(P)
    print("Câu 3a: Ma trận P khả nghịch.")
    print("P⁻¹ =\n", np.round(P_inv, 3))
except np.linalg.LinAlgError:
    print("Câu 3a: Ma trận P không khả nghịch.")

# ===== b) Giải hệ Px = b =====
x = np.dot(P_inv, b)
print("\nCâu 3b: Nghiệm của hệ là:")
print("x =", np.round(x, 3))

# ===== c) Kiểm tra nghiệm =====
check = np.dot(P, x)
print("\nCâu 3c: Kiểm tra P * x =")
print(np.round(check, 3))
print("→ Khớp với vector b:", np.allclose(check, b))

Câu 3a: Ma trận P khả nghịch.
P⁻¹ =
 [[ 0.488 -0.093  0.023 -0.209]
 [ 0.035  0.279 -0.07   0.128]
 [-0.116  0.07   0.233 -0.093]
 [-0.012 -0.093  0.023  0.291]]

Câu 3b: Nghiệm của hệ là:
x = [0.465 2.105 1.651 0.965]

Câu 3c: Kiểm tra P * x =
[4. 7. 9. 5.]
→ Khớp với vector b: True


In [9]:
import numpy as np

# ===== Câu 4: Ma trận Q =====
Q = np.array([
    [4, -1, 0],
    [1, 3, -2],
    [0, 1, 2]
])

# ===== a) Tìm giá trị riêng =====
eigenvalues, eigenvectors = np.linalg.eig(Q)

print("Câu 4a: Giá trị riêng (eigenvalues):")
print(np.round(eigenvalues, 3))

# ===== b) Tìm vector riêng =====
print("\nCâu 4b: Vector riêng (cột ứng với từng giá trị riêng):")
print(np.round(eigenvectors, 3))

# ===== c) Chuẩn hóa vector riêng =====
print("\nCâu 4c: Vector riêng sau khi chuẩn hóa:")
for vec in eigenvectors.T:
    norm_vec = vec / np.linalg.norm(vec)
    print(np.round(norm_vec, 3))


Câu 4a: Giá trị riêng (eigenvalues):
[3.453+0.j    2.773+1.468j 2.773-1.468j]

Câu 4b: Vector riêng (cột ứng với từng giá trị riêng):
[[ 0.833+0.j    -0.262-0.314j -0.262+0.314j]
 [ 0.455+0.j    -0.782+0.j    -0.782-0.j   ]
 [ 0.313+0.j    -0.22 +0.417j -0.22 -0.417j]]

Câu 4c: Vector riêng sau khi chuẩn hóa:
[0.833+0.j 0.455+0.j 0.313+0.j]
[-0.262-0.314j -0.782+0.j    -0.22 +0.417j]
[-0.262+0.314j -0.782+0.j    -0.22 -0.417j]


In [10]:
import numpy as np

# ===== Câu 5: Dữ liệu =====
R = np.array([
    [1, -2, 3],
    [2, 0, 1],
    [-1, 1, 4]
])

b = np.array([10, 8, 7])

# ===== a) Giải hệ Rx = b =====
x = np.linalg.solve(R, b)
print("Câu 5a: Nghiệm của hệ Rx = b là:")
print(np.round(x, 3))

# ===== b) Kiểm tra khả nghịch & giải lại hệ bằng nghịch đảo =====
det_R = np.linalg.det(R)
if det_R != 0:
    R_inv = np.linalg.inv(R)
    x2 = np.dot(R_inv, b)
    print("\nCâu 5b: Ma trận R khả nghịch (det ≠ 0)")
    print("Nghiệm bằng R⁻¹ · b:", np.round(x2, 3))
    print("Hai nghiệm có giống nhau không?", np.allclose(x, x2))
else:
    print("\nCâu 5b: Ma trận R không khả nghịch.")

# ===== c) Tính chuẩn Frobenius của R =====
fro_norm = np.linalg.norm(R, 'fro')
print("\nCâu 5c: Chuẩn Frobenius của R =", round(fro_norm, 3))

Câu 5a: Nghiệm của hệ Rx = b là:
[2.783 0.043 2.435]

Câu 5b: Ma trận R khả nghịch (det ≠ 0)
Nghiệm bằng R⁻¹ · b: [2.783 0.043 2.435]
Hai nghiệm có giống nhau không? True

Câu 5c: Chuẩn Frobenius của R = 6.083
